FROM docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2

#RUN rm /usr/share/logstash/config/logstash-sample.conf
#RUN rm /usr/share/logstash/config/logstash-opensearch-sample.conf
#RUN rm /usr/share/logstash/config/pipelines.yml
#COPY config/logstash-windows-events.conf /usr/share/logstash/config/
#COPY config/pipelines.yml /usr/share/logstash/config/
